$ErrorActionPreference = "Stop"

function Read-ToolInput {
    $raw = [Console]::In.ReadToEnd()
    if ([string]::IsNullOrWhiteSpace($raw)) {
        return @{}
    }

    $parsed = $raw | ConvertFrom-Json -Depth 16
    if ($null -eq $parsed) {
        return @{}
    }

    return $parsed
}

function ConvertTo-Hashtable {
    param($Value)

    if ($null -eq $Value) {
        return @{}
    }

    if ($Value -is [System.Collections.IDictionary]) {
        return $Value
    }

    $table = @{}
    foreach ($property in $Value.PSObject.Properties) {
        $table[$property.Name] = $property.Value
    }
    return $table
}

function Format-Argument {
    param([string]$Value)

    if ($null -eq $Value) {
        return '""'
    }

    $escaped = $Value.Replace('"', '\"')
    if ($escaped -match '\s|"') {
        return '"' + $escaped + '"'
    }

    return $escaped
}

function Join-Arguments {
    param([object[]]$Arguments)

    if ($null -eq $Arguments -or $Arguments.Count -eq 0) {
        return ""
    }

    return (($Arguments | ForEach-Object { Format-Argument ([string]$_) }) -join ' ')
}

function Resolve-CandidateCommands {
    return @(
        "clia",
        "cli-anything",
        "anything-cli",
        "anything"
    )
}

function Resolve-Command {
    param(
        [string]$RequestedCommand
    )

    if (-not [string]::IsNullOrWhiteSpace($RequestedCommand)) {
        return @{
            command = $RequestedCommand
            source = "input"
        }
    }

    if (-not [string]::IsNullOrWhiteSpace($env:CLI_ANYTHING_COMMAND)) {
        return @{
            command = $env:CLI_ANYTHING_COMMAND
            source = "CLI_ANYTHING_COMMAND"
        }
    }

    foreach ($candidate in Resolve-CandidateCommands) {
        $resolved = Get-Command $candidate -ErrorAction SilentlyContinue
        if ($null -ne $resolved) {
            return @{
                command = $resolved.Source
                source = "detected"
            }
        }
    }

    return $null
}

function New-JsonResult {
    param($Payload)
    $Payload | ConvertTo-Json -Depth 16 -Compress
}

function Invoke-StatusTool {
    param($InputObject)

    $requested = ""
    if ($null -ne $InputObject.command) {
        $requested = [string]$InputObject.command
    }

    $resolved = Resolve-Command $requested
    $python = Get-Command python -ErrorAction SilentlyContinue
    $pip = Get-Command pip -ErrorAction SilentlyContinue

    New-JsonResult @{
        plugin = $env:CLAW_PLUGIN_ID
        tool = $env:CLAW_TOOL_NAME
        available = $null -ne $resolved
        configuredCommand = if ([string]::IsNullOrWhiteSpace($env:CLI_ANYTHING_COMMAND)) { $null } else { $env:CLI_ANYTHING_COMMAND }
        detectedCommand = if ($null -eq $resolved) { $null } else { $resolved.command }
        commandSource = if ($null -eq $resolved) { $null } else { $resolved.source }
        candidateCommands = Resolve-CandidateCommands
        pythonAvailable = $null -ne $python
        pipAvailable = $null -ne $pip
        pluginRoot = $env:CLAW_PLUGIN_ROOT
        note = "If you use a CLI generated by CLI-Anything, pass its executable explicitly via command."
    }
}

function Invoke-RunTool {
    param($InputObject)

    $requested = if ($null -ne $InputObject.command) { [string]$InputObject.command } else { "" }
    $resolved = Resolve-Command $requested
    if ($null -eq $resolved) {
        return New-JsonResult @{
            ok = $false
            error = "No CLI-Anything command was detected. Install CLI-Anything, pass command explicitly, or set CLI_ANYTHING_COMMAND."
            candidateCommands = Resolve-CandidateCommands
        }
    }

    $arguments = @()
    if ($null -ne $InputObject.args) {
        foreach ($item in $InputObject.args) {
            $arguments += [string]$item
        }
    }

    $workingDirectory = if ($null -ne $InputObject.workingDirectory -and -not [string]::IsNullOrWhiteSpace([string]$InputObject.workingDirectory)) {
        [string]$InputObject.workingDirectory
    } elseif (-not [string]::IsNullOrWhiteSpace($env:CLAW_PLUGIN_ROOT)) {
        $env:CLAW_PLUGIN_ROOT
    } else {
        (Get-Location).Path
    }

    $timeoutSeconds = 120
    if ($null -ne $InputObject.timeoutSeconds) {
        $timeoutSeconds = [int]$InputObject.timeoutSeconds
    }

    $psi = New-Object System.Diagnostics.ProcessStartInfo
    $psi.FileName = [string]$resolved.command
    $psi.Arguments = Join-Arguments $arguments
    $psi.WorkingDirectory = $workingDirectory
    $psi.UseShellExecute = $false
    $psi.RedirectStandardInput = $true
    $psi.RedirectStandardOutput = $true
    $psi.RedirectStandardError = $true
    $psi.CreateNoWindow = $true

    $extraEnv = ConvertTo-Hashtable $InputObject.env
    foreach ($entry in $extraEnv.GetEnumerator()) {
        $psi.Environment[$entry.Key] = [string]$entry.Value
    }

    $process = New-Object System.Diagnostics.Process
    $process.StartInfo = $psi
    [void]$process.Start()

    if ($null -ne $InputObject.stdin -and $process.StartInfo.RedirectStandardInput) {
        $process.StandardInput.Write([string]$InputObject.stdin)
    }
    $process.StandardInput.Close()

    $completed = $process.WaitForExit($timeoutSeconds * 1000)
    if (-not $completed) {
        try {
            $process.Kill()
        } catch {
        }

        return New-JsonResult @{
            ok = $false
            timeout = $true
            command = $resolved.command
            commandSource = $resolved.source
            workingDirectory = $workingDirectory
            timeoutSeconds = $timeoutSeconds
            error = "CLI-Anything command timed out."
        }
    }

    $stdout = $process.StandardOutput.ReadToEnd()
    $stderr = $process.StandardError.ReadToEnd()

    return New-JsonResult @{
        ok = ($process.ExitCode -eq 0)
        exitCode = $process.ExitCode
        command = $resolved.command
        commandSource = $resolved.source
        args = $arguments
        workingDirectory = $workingDirectory
        stdout = $stdout.TrimEnd()
        stderr = $stderr.TrimEnd()
    }
}

try {
    $inputObject = Read-ToolInput
    switch ($env:CLAW_TOOL_NAME) {
        "cli_anything_status" {
            Write-Output (Invoke-StatusTool $inputObject)
        }
        "cli_anything_run" {
            Write-Output (Invoke-RunTool $inputObject)
        }
        default {
            Write-Output (New-JsonResult @{
                ok = $false
                error = "unsupported CLI-Anything bridge tool: $($env:CLAW_TOOL_NAME)"
            })
        }
    }
} catch {
    Write-Output (New-JsonResult @{
        ok = $false
        error = $_.Exception.Message
    })
}
